### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by poudenes** [tweaker/homeassistant-binance#4]
Hi with latest HA its not working:

2021-04-27 14:21:45 ERROR (MainThread) [custom_components.binance.sensor] Error fetching data from binance.com
2021-04-27 14:21:45 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up binance platform for sensor

**Comment by tatawi** [comment]
You can try to add version in manifest.json file : 
{
  "domain": "binance",
  "name": "Binance course sensors",
  "documentation": "https://github.com/tweaker/binance",
  **"version": "1.0.2",**
  "dependencies": [],
  "codeowners": ["@tweaker"],
  "requirements": ["python-binance==0.7.1"]
}

**Comment by andreasc1** [comment]
> You can try to add version in manifest.json file :
> {
> "domain": "binance",
> "name": "Binance course sensors",
> "documentation": "https://github.com/tweaker/binance",
> **"version": "1.0.2",**
> "dependencies": [],
> "codeowners": ["@tweaker"],
> "requirements": ["python-binance==0.7.1"]
> }

added the version but still it doesn't work.
